#ifndef _BITMAP_H_
#define _BITMAP_H_


extern const unsigned char Bitmap_100_fill [];
extern const unsigned char Bitmap_101_fill [];
extern const unsigned char Bitmap_102_fill [];
extern const unsigned char Bitmap_103_fill [];
extern const unsigned char Bitmap_104_fill [];
extern const unsigned char Bitmap_150_fill [];
extern const unsigned char Bitmap_151_fill [];
extern const unsigned char Bitmap_152_fill [];
extern const unsigned char Bitmap_153_fill [];
extern const unsigned char Bitmap_300_fill [];
extern const unsigned char Bitmap_301_fill [];
extern const unsigned char Bitmap_302_fill [];
extern const unsigned char Bitmap_303_fill [];
extern const unsigned char Bitmap_304_fill [];
extern const unsigned char Bitmap_305_fill [];
extern const unsigned char Bitmap_306_fill [];
extern const unsigned char Bitmap_307_fill [];
extern const unsigned char Bitmap_308_fill [];
extern const unsigned char Bitmap_309_fill [];
extern const unsigned char Bitmap_310_fill [];
extern const unsigned char Bitmap_311_fill [];
extern const unsigned char Bitmap_312_fill [];
extern const unsigned char Bitmap_313_fill [];
extern const unsigned char Bitmap_314_fill [];
extern const unsigned char Bitmap_315_fill [];
extern const unsigned char Bitmap_316_fill [];
extern const unsigned char Bitmap_317_fill [];
extern const unsigned char Bitmap_318_fill [];
extern const unsigned char Bitmap_350_fill [];
extern const unsigned char Bitmap_351_fill [];
extern const unsigned char Bitmap_399_fill [];
extern const unsigned char Bitmap_400_fill [];
extern const unsigned char Bitmap_401_fill [];
extern const unsigned char Bitmap_402_fill [];
extern const unsigned char Bitmap_403_fill [];
extern const unsigned char Bitmap_404_fill [];
extern const unsigned char Bitmap_405_fill [];
extern const unsigned char Bitmap_406_fill [];
extern const unsigned char Bitmap_407_fill [];
extern const unsigned char Bitmap_408_fill [];
extern const unsigned char Bitmap_409_fill [];
extern const unsigned char Bitmap_410_fill [];
extern const unsigned char Bitmap_456_fill [];
extern const unsigned char Bitmap_457_fill [];
extern const unsigned char Bitmap_499_fill [];
extern const unsigned char Bitmap_500_fill [];
extern const unsigned char Bitmap_501_fill [];
extern const unsigned char Bitmap_502_fill [];
extern const unsigned char Bitmap_503_fill [];
extern const unsigned char Bitmap_504_fill [];
extern const unsigned char Bitmap_507_fill [];
extern const unsigned char Bitmap_508_fill [];
extern const unsigned char Bitmap_509_fill [];
extern const unsigned char Bitmap_510_fill [];
extern const unsigned char Bitmap_511_fill [];
extern const unsigned char Bitmap_512_fill [];
extern const unsigned char Bitmap_513_fill [];
extern const unsigned char Bitmap_514_fill [];
extern const unsigned char Bitmap_515_fill [];
extern const unsigned char Bitmap_900_fill [];
extern const unsigned char Bitmap_901_fill [];
extern const unsigned char Bitmap_999_fill [];
extern const unsigned char Bitmap_local [];
// 16x16
extern const unsigned char Bitmap_100_fill_16[32];
extern const unsigned char Bitmap_101_fill_16[32];
extern const unsigned char Bitmap_102_fill_16[32];
extern const unsigned char Bitmap_103_fill_16[32];
extern const unsigned char Bitmap_104_fill_16[32];
extern const unsigned char Bitmap_150_fill_16[32];
extern const unsigned char Bitmap_151_fill_16[32];
extern const unsigned char Bitmap_152_fill_16[32];
extern const unsigned char Bitmap_153_fill_16[32];
extern const unsigned char Bitmap_300_fill_16[32];
extern const unsigned char Bitmap_301_fill_16[32];
extern const unsigned char Bitmap_302_fill_16[32];
extern const unsigned char Bitmap_303_fill_16[32];
extern const unsigned char Bitmap_304_fill_16[32];
extern const unsigned char Bitmap_305_fill_16[32];
extern const unsigned char Bitmap_306_fill_16[32];
extern const unsigned char Bitmap_307_fill_16[32];
extern const unsigned char Bitmap_308_fill_16[32];
extern const unsigned char Bitmap_309_fill_16[32];
extern const unsigned char Bitmap_310_fill_16[32];
extern const unsigned char Bitmap_311_fill_16[32];
extern const unsigned char Bitmap_312_fill_16[32];
extern const unsigned char Bitmap_313_fill_16[32];
extern const unsigned char Bitmap_314_fill_16[32];
extern const unsigned char Bitmap_315_fill_16[32];
extern const unsigned char Bitmap_316_fill_16[32];
extern const unsigned char Bitmap_317_fill_16[32];
extern const unsigned char Bitmap_318_fill_16[32];
extern const unsigned char Bitmap_350_fill_16[32];
extern const unsigned char Bitmap_351_fill_16[32];
extern const unsigned char Bitmap_399_fill_16[32];
extern const unsigned char Bitmap_400_fill_16[32];
extern const unsigned char Bitmap_401_fill_16[32];
extern const unsigned char Bitmap_402_fill_16[32];
extern const unsigned char Bitmap_403_fill_16[32];
extern const unsigned char Bitmap_404_fill_16[32];
extern const unsigned char Bitmap_405_fill_16[32];
extern const unsigned char Bitmap_406_fill_16[32];
extern const unsigned char Bitmap_407_fill_16[32];
extern const unsigned char Bitmap_408_fill_16[32];
extern const unsigned char Bitmap_409_fill_16[32];
extern const unsigned char Bitmap_410_fill_16[32];
extern const unsigned char Bitmap_456_fill_16[32];
extern const unsigned char Bitmap_457_fill_16[32];
extern const unsigned char Bitmap_499_fill_16[32];
extern const unsigned char Bitmap_500_fill_16[32];
extern const unsigned char Bitmap_501_fill_16[32];
extern const unsigned char Bitmap_502_fill_16[32];
extern const unsigned char Bitmap_503_fill_16[32];
extern const unsigned char Bitmap_504_fill_16[32];
extern const unsigned char Bitmap_507_fill_16[32];
extern const unsigned char Bitmap_508_fill_16[32];
extern const unsigned char Bitmap_509_fill_16[32];
extern const unsigned char Bitmap_510_fill_16[32];
extern const unsigned char Bitmap_511_fill_16[32];
extern const unsigned char Bitmap_512_fill_16[32];
extern const unsigned char Bitmap_513_fill_16[32];
extern const unsigned char Bitmap_514_fill_16[32];
extern const unsigned char Bitmap_515_fill_16[32];
extern const unsigned char Bitmap_900_fill_16[32];
extern const unsigned char Bitmap_901_fill_16[32];
extern const unsigned char Bitmap_999_fill_16[32];
extern const unsigned char Bitmap_local [];
extern const unsigned char jitang[];

#endif